-- MySQL Script generated by MySQL Workbench
-- Mon Nov 15 19:58:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema malan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `malan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `malan` ;

-- -----------------------------------------------------
-- Table `malan`.`choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malan`.`choice` (
  `CHOICE_ID` INT NOT NULL AUTO_INCREMENT,
  `REGID` INT NULL DEFAULT NULL,
  `color` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`CHOICE_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `malan`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malan`.`persons` (
  `PersonID` INT NULL DEFAULT NULL,
  `LastName` VARCHAR(255) NULL DEFAULT NULL,
  `FirstName` VARCHAR(255) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `City` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `malan`.`reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malan`.`reg` (
  `REGID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`REGID`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
